version: "3"

services:
        nginx:
                build: .docker/nginx
                container_name: nginx
                restart: always
                tty: true
                ports:
                        - "8000:80"
                volumes:
                        - .:/var/www
                networks:
                        - app-network
                depends_on:
                        - app
                        
        app:
                build: .
                container_name: app
                entrypoint: dockerize -template ./.docker/app/.env:.env -template ./.docker/nginx/nginx_template.conf:./.docker/nginx/nginx.conf -wait tcp://db:3306 -timeout 120s .docker/entrypoint.sh
                #entrypoint: dockerize -wait tcp://db:3306 -timeout 120s .docker/entrypoint.sh
                volumes:
                        - .:/var/www
                networks:
                        - app-network
                environment:
                        - DB_USERNAME=root
                        - DB_PASSWORD=root
                        - DB_DATABASE=laravel
                        - DB_HOST=db
                        - DB_PORT=3306
                        - SERVER_HOST=app
                        - SERVER_PORT=9000
                depends_on:
                        - db
                        - redis

        db:
                build: .docker/mysql
                command: --innodb-use-native-aio=0
                container_name: db
                restart: always
                tty: true
                ports:
                        - "3306:3306"
                volumes:
                        - ./.docker/dbdata:/var/lib/mysql
                environment:
                        - MYSQL_USER=root
                        - MYSQL_PASSWORD=root
                        - MYSQL_ROOT_PASSWORD=root
                        - MYSQL_DATABASE=laravel

                networks:
                        - app-network

        redis:
                image: redis:alpine
                expose:
                        - 6397
                networks:
                        - app-network

networks:
        app-network:
                driver: bridge
